# --- Kafka Streams ---
quarkus.kafka-streams.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:29092}
quarkus.kafka-streams.application-id=arena-${GROUPE:grp00}
# Quarkus attend que ces topics existent avant de demarrer la topologie
quarkus.kafka-streams.topics=arena.match.events,arena.purchases,arena.players

# Passthrough vers Kafka Streams
kafka-streams.auto.offset.reset=earliest
# Bonus fiabilite :
# kafka-streams.processing.guarantee=exactly_once_v2

# --- Regles de session (ARN-5), surchargeables a l'oral ---
SESSION_GAP_MINUTES=${SESSION_GAP_MINUTES:5}
MARATHON_MINUTES=${MARATHON_MINUTES:12}

# --- HTTP (si vous exposez une API Interactive Queries en extra) ---
# 8080 est pris par Kafbat UI dans le docker-compose fourni
quarkus.http.port=8090

quarkus.log.category."fr.esgi.kafka".level=INFO
