# --- Kafka Streams ---
quarkus.kafka-streams.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:29092}
quarkus.kafka-streams.application-id=forge-${GROUPE:grp00}
# Quarkus attend que ces topics existent avant de demarrer la topologie
quarkus.kafka-streams.topics=forge.readings,forge.production,forge.machines

# Passthrough vers Kafka Streams
kafka-streams.auto.offset.reset=earliest
# Bonus fiabilite :
# kafka-streams.processing.guarantee=exactly_once_v2

# --- Surveillance des machines muettes (FOR-5), surchargeable a l'oral ---
SILENCE_MINUTES=${SILENCE_MINUTES:8}

# --- HTTP (si vous exposez une API Interactive Queries en extra) ---
# 8080 est pris par Kafbat UI dans le docker-compose fourni
quarkus.http.port=8090

quarkus.log.category."fr.esgi.kafka".level=INFO
