# --- Kafka Streams ---
quarkus.kafka-streams.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:29092}
quarkus.kafka-streams.application-id=dispatch-${GROUPE:grp00}
# Quarkus attend que ces topics existent avant de demarrer la topologie
quarkus.kafka-streams.topics=dispatch.ride.requests,dispatch.driver.locations,dispatch.trip.events

# Passthrough vers Kafka Streams
kafka-streams.auto.offset.reset=earliest
# Bonus fiabilite (DISP-6) :
# kafka-streams.processing.guarantee=exactly_once_v2

# --- HTTP (bonus Interactive Queries) ---
# 8080 est pris par Kafbat UI dans le docker-compose fourni
quarkus.http.port=8090

quarkus.log.category."fr.esgi.kafka".level=INFO
