# --- Kafka Streams ---
quarkus.kafka-streams.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:29092}
quarkus.kafka-streams.application-id=relay-${GROUPE:grp00}
# Quarkus attend que ces topics existent avant de demarrer la topologie
quarkus.kafka-streams.topics=relay.impressions,relay.clicks,relay.campaigns

# Passthrough vers Kafka Streams
kafka-streams.auto.offset.reset=earliest
# Bonus fiabilite :
# kafka-streams.processing.guarantee=exactly_once_v2

# --- Fenetre anti-robot (RLY-5), surchargeable a l'oral ---
BOT_WINDOW_MINUTES=${BOT_WINDOW_MINUTES:10}

# --- HTTP (si vous exposez une API Interactive Queries en extra) ---
# 8080 est pris par Kafbat UI dans le docker-compose fourni
quarkus.http.port=8090

quarkus.log.category."fr.esgi.kafka".level=INFO
